version: '3.9'
services:
  client:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      - ./package-lock.json:/app/package-lock.json
      - ./package.json:/app/package.json
      - /app/node_modules
    ports:
      - '3000:3000'
    restart: always
