import { FC, PropsWithChildren } from 'react';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout: FC<PropsWithChildren> = (props) => {
  const { children } = props;

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
